[build]
builder = "NIXPACKS"
buildCommand = "cd kolsch-main && npm ci && npm run build"

[deploy]
startCommand = "cd kolsch-main && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[build.nixpacks.phases.setup]]
nixPkgs = ["nodejs_20"]